function prefs = createModelPreferences(lowScale,highScale,blockMemory,percentCal,percentVal)

% Siyu: commented out two unneeded preferences below
% daysToExtend = memoryDays + memoryAverages*lengthOfAverage + blockMemory;
% dataTimewindow = extendTimeWindow(timewindow,daysToExtend,'front');

prefs = struct('lowScale',       lowScale,...
               'highScale',      highScale,...
               'blockMemory',    blockMemory,...
               'ANNconfig',      ' ',...
               'percentCal',     percentCal,...
               'percentVal',     percentVal);

           